### Open-source vs. Official datasets

All of the data sources we draw from are open-source, "unofficial" datasets.  The data are not drawn from mandatory government reporting on deaths caused by law enforcement officers because there is no official national data program designed for this purpose that is currently functioning.  The open-source datasets rely on cases known/discovered by the respective project teams, primarily identified using a battery of online searches and a mix of automated and manual coding.


In theory, deaths caused by police should also be captured by several official data collection programs:  

* the [National Vital Statistics System](https://www.cdc.gov/violenceprevention/datasources/nvdrs/index.html), which collects death certificates.

* the [Arrest Related Death](https://bjs.ojp.gov/data-collection/arrest-related-deaths-ard) program, run by the Bureau of Justice Statistics (BJS), ended in 2012.

* the [Supplementary/Expanded Homicide Reports](https://ucr.fbi.gov/crime-in-the-u.s/2019/crime-in-the-u.s.-2019/tables/expanded-homicide-data-table-14.xls) program, run by the the Federal Bureau of Investigation (FBI), based on the Uniform Crime Reporting program.

* the [National Violent Deaths Reporting System](https://www.cdc.gov/violenceprevention/datasources/nvdrs/index.html), a newer program run by the Centers for Disease Control and Prevention (CDC), all states reporting as of 2018, though reporting is not yet complete for the recently added states.  WA State has been reporting from all counties as of 2018; more information
can be found [here](https://doh.wa.gov/you-and-your-family/injury-and-violence-prevention/washington-state-violent-death-reporting-system).

* the [National Use of Force](https://www.fbi.gov/how-we-can-help-you/more-fbi-services-and-information/ucr/use-of-force) reporting program run by the FBI.  Qualifying uses of force include any action that resulted in the death or serious bodily injury of a person, or the discharge of a firearm at or in the direction of a person.  Agency participation is voluntary, data collection began in 2019.  In 2025, 12,035 out of 19,277 federal, state, local, and tribal law enforcement agencies throughout the nation participated and provided use-of-force data. The officers employed by these agencies represent 78% federal, state, local, and tribal sworn officers in the nation.  This is below the 80% coverage level required to release national data to the public.  For WA, 51 out of 276 agencies in Washington participated, representing 48% of sworn law enforcement officers in the state.  Among participating agencies the number reporting use of force ranged from 0 to 3 agencies each month over the last 12 months of data.

#### Why we don't use the official data

* *Studies have repeatedly shown that official programs consistently fail to identify about half of the people killed by police.*

The most recent study to have replicated this finding was conducted by the [Institute for Health Metrics and Evaluation](https://www.healthdata.org/about) in 2021, and published in the [Lancet](https://www.thelancet.com/).  You can access the study [here](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)01609-3/fulltext), and less technical summaries [can be found in the news media](https://www.cnn.com/2021/09/30/us/study-police-deaths-undercount/index.html).  Other studies show similar rates of undercounting in the Arrest Related Death and Supplementary Homicide Reporting systems, one example is [here](https://www.ojp.gov/library/publications/assessment-coverage-arrest-related-deaths-program).  

The one exception to this is the National Violent Deaths Reporting system.  A [study from 2016](https://pmc.ncbi.nlm.nih.gov/articles/PMC4985110/) showed that NVDRS had better coverage of police killings than the other federal sources, and another [study from 2015](https://ajph.aphapublications.org/doi/full/10.2105/AJPH.2018.304904) found that it captured almost all of the people shot and killed by police in the 27 states that were participating in the program at the time -- but note that the number used to assess NVDRS coverage was based largely on the number found in open-source datasets.  There has been no update since the state coverage reached all 50 states in 2018, and there has been no assessment of its coverage of deaths due to causes other than gunshot.  Perhaps most importantly, the 2015 study simply showed that this dataset had comparable coverage to the open-source datasets, not that it was superior.

* *Federal research has also shown that the methodology used by the open-source data sets is effective*

A 2019 assessment by the Bureau of Justice Statistics (BJS) concluded that:

  "Findings indicate that the open-source methodology alone identifies the majority of law enforcement homicides, but agency surveys aid in identifying deaths by other causes (e.g., accidents, suicides, and natural causes)."  [BJS 2019](https://www.ojp.gov/library/publications/arrest-related-deaths-program-pilot-study-redesigned-survey-methodology)


* *Official datasets lack contextual information*

The other key benefit to the open-source datasets is that every case includes a link to publicly available documentation that verifies the case and serves as a starting place for additional research.  This allows us to identify the law enforcement agency(ies) involved, provides more context and sometimes reveals conflicting narratives as to the events.  All of this helps to remind us that each case is a person, not just a statistic.

_____

> At this point, it is widely acknowleged that the open-source datasets have the most complete coverage of these cases.  That is why we use them here.

_____

That said, it is important to keep in mind that these open-source datasets, too, are not perfect.   They will miss cases that have not generated a digital signature that can be found using their search methodologies.  So it would be accurate to say that our open-source data provide a lower bound estimate of the number of people killed by police; the true value is likely higher, but it can not be lower.


  
### Exclusions

Cases reported as suicides and coded as "Medical Emergencies" are excluded from the analyses in this report.

*Suicides*

FE, IN and WA local include some cases classified as "suicides" that occur during an encounter with police.  These are not cases of "suicide by cop", where the victim appears to have provoked the police in order to be killed.  They are cases where the victim shoots or otherwise takes their own life.  **We have excluded these from the analyses in this report, because the report focuses on persons killed by police.**  

We acknowledge that these cases warrant further assessment.  It is not uncommon that officers did shoot at the suspect, but missed or failed to kill them.  In addition the classification as "suicide" may not be definitive, if it is based on the narrative provided by law enforcement to the media at the time rather than a subsequent investigation by the local coroner or medical examiner.  Finally, even if these are suicides, it is possible that the outcome might have been different if the case had been handled differently, for example, by calling in a crisis intervention team and deescalating effectively.

The excluded case counts and fraction of total cases by year is shown in the table below.

```{r tabSuicide}

tab <- wa_clean_2015 %>%
  mutate(suicide = if_else(mod=="Suicide", "Suicide", "All other deaths")) %>%
  group_by(Year=year, suicide) %>%
  count() %>%
  pivot_wider(names_from = suicide,
              values_from = n)%>%
  replace_na(list(Suicide=0)) %>%
  mutate(Year = as.character(Year)) %>%
  mutate(Total = sum(across(where(is.numeric))),
         Percent = round(100*Suicide/Total, 1),
         ) %>%
  select(Year, Number=Suicide, Percent) %>%
  bind_rows(data.frame(Year ="Total", 
                       Number = sum(.$Number), 
                       Percent = round(100*sum(.$Number)/nrow(wa_clean_2015), 1)))

tab %>%
  kable(caption = "Cases labeled 'Suicide' by year*",
        col.names = c("year", "Number", "% of Cases")) %>%
  kable_styling(bootstrap_options = c("striped","hover"),
                full_width = F) %>%
  row_spec(dim(tab)[1], bold = T)  %>%
  add_footnote(label = "These cases were excluded from analyses in this report",
               notation = "symbol")
```

*Medical Emergencies*

There are also a handful of cases where the cause of death is coded as "Medical emergency".  We exclude these cases from this report as well, as they do not meet the definition of "homicide."  But we note that in all of these cases, there was substantial interaction with the police in the period preceding the death, and the person died in police custody.  The cases in WA involved such things as lengthy vehicular pursuits, physical restraints, and injection with something to "calm them down" (presumably Ketamine).

___


